### ISSUE TITLE
Mapping discussion  OJP->Nova

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#12]
ns3:verkehrsMittel@ns3:verkehrsMittelNummer is wrong it should come  from ojp:Extension/ojp:PublishedJourneyNumber
I find a timed_leg.extension, but then I got stuck on how to read from the AnyElement
very thing in the updates_mg_1 branch

**Comment by skinkie** [comment]
https://github.com/tefra/xsdata/issues/635

**Comment by ue71603** [comment]
didn't help me. I didn't even find a FAQ related to the topic.

**Comment by skinkie** [comment]
https://github.com/tefra/xsdata/commit/0b2a08506105213cb85c253bb21b691d7f4a96ad

It basically is exposed. If you cannot get it, I'll do it later.

**Comment by ue71603** [comment]
look at the beautiful hack I did.....  and I think we get now also discount tickets with strange ns1:produktNummer

**Comment by ue71603** [comment]
but I guess you can do it way more elegantly than: 
`  e=timed_leg.extension
    p=e.__getattribute__('children')
    i=0
    t=""
    while (i<len(p)):
        qn=p[i].__getattribute__('qname')
        if (qn=='{http://www.vdv.de/ojp}PublishedJourneyNumber'):
            le=p[i].__getattribute__('children')
            j=0
            while (j<len(le)):
                t=le[j].__getattribute__('text')
                j=j+1
        i=i+1
    if (len(t)==0):
        print('extraction of Extension/PublishedJourneyName went wrong')
        exit(1)
    verkehrs_mittel_nummer=t`

**Comment by skinkie** [comment]
...my eyes
