### ISSUE TITLE
HTTPS: How will we do https?

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#16]
We need a longer call in server.py:
    uvicorn.run(
        'main:app', port=443, host='0.0.0.0',
        reload=True, reload_dirs=['html_files'],
        ssl_keyfile='/path/to/certificate-key.pem',
        ssl_certfile='/path/to/certificate.pem')

and we need ssl_key/certificate. I think we can only do this later.
Perhaps we need a switch that tells if the service should be http or https:  I will add some parts now.

**Comment by skinkie** [comment]
What do you mean exactly?

**Comment by ue71603** [comment]
at some point the service should not be http but https, I guess. Currently http is hardcoded

**Comment by skinkie** [comment]
You mean accessing upstream?

**Comment by ue71603** [comment]
implemented it.
