### ISSUE TITLE
Problem with the conversion of a data

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#29]
The following request resulted in a conversion problem.

### Error:
D:\development\2023-04_ojpfare2nova\ojp-nova-master\venv\lib\site-packages\xsdata\formats\converter.py:83: ConverterWarning: Failed to convert value `2023-08-08T12:51:28+0200` to one of (<class 'xsdata.models.datatype.XmlDateTime'>,)
  warnings.warn(

Request (in SOAPUI):

`<?xml version="1.0" encoding="UTF-8"?>
<OJP xmlns="http://www.siri.org.uk/siri" xmlns:ojp="http://www.vdv.de/ojp" version="1.0">
  <OJPRequest>
    <ServiceRequest>
      <RequestTimestamp>2023-05-15T11:53:30.943074Z</RequestTimestamp>
      <RequestorRef>OJP2NOVA</RequestorRef>
      <ojp:OJPTripRequest>
        <RequestTimestamp>2023-05-15T11:53:30.943074Z</RequestTimestamp>
        <ojp:Origin>
          <ojp:PlaceRef>
            <StopPointRef>8507000</StopPointRef>
            <ojp:LocationName>
              <ojp:Text>origin</ojp:Text>
            </ojp:LocationName>
          </ojp:PlaceRef>
          <ojp:DepArrTime>${=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(new Date())}</ojp:DepArrTime>
        </ojp:Origin>
        <ojp:Destination>
          <ojp:PlaceRef>
            <StopPointRef>8504221</StopPointRef>
            <ojp:LocationName>
              <ojp:Text>destination</ojp:Text>
            </ojp:LocationName>
          </ojp:PlaceRef>
        </ojp:Destination>
        <ojp:Params>
          <ojp:NumberOfResults>1</ojp:NumberOfResults>
          <ojp:IncludeTrackSections>false</ojp:IncludeTrackSections>
          <ojp:IncludeLegProjection>false</ojp:IncludeLegProjection>
          <ojp:IncludeTurnDescription>false</ojp:IncludeTurnDescription>
          <ojp:IncludeIntermediateStops>true</ojp:IncludeIntermediateStops>
        </ojp:Params>
      </ojp:OJPTripRequest>
    </ServiceRequest>
  </OJPRequest>
</OJP>`

**Comment by skinkie** [comment]
I want to receive the original failing request.

**Comment by skinkie** [comment]
Reproduce with:
```python
from map_ojp_to_ojp import parse_ojp
x = """<?xml version="1.0" encoding="UTF-8"?> <OJP xmlns="http://www.siri.org.uk/siri" xmlns:ojp="http://www.vdv.de/ojp" version="1.0"> <OJPRequest> <ServiceRequest> <RequestTimestamp>2023-05-15T11:53:30.943074Z</RequestTimestamp> <RequestorRef>OJP2NOVA</RequestorRef> <ojp:OJPTripRequest> <RequestTimestamp>2023-05-15T11:53:30.943074Z</RequestTimestamp> <ojp:Origin> <ojp:PlaceRef> <StopPointRef>8507000</StopPointRef> <ojp:LocationName> <ojp:Text>origin</ojp:Text> </ojp:LocationName> </ojp:PlaceRef> <ojp:DepArrTime>2023-08-08T12:51:28+0200</ojp:DepArrTime> </ojp:Origin> <ojp:Destination> <ojp:PlaceRef> <StopPointRef>8504221</StopPointRef> <ojp:LocationName> <ojp:Text>destination</ojp:Text> </ojp:LocationName> </ojp:PlaceRef> </ojp:Destination> <ojp:Params> <ojp:NumberOfResults>1</ojp:NumberOfResults> <ojp:IncludeTrackSections>false</ojp:IncludeTrackSections> <ojp:IncludeLegProjection>false</ojp:IncludeLegProjection> <ojp:IncludeTurnDescription>false</ojp:IncludeTurnDescription> <ojp:IncludeIntermediateStops>true</ojp:IncludeIntermediateStops> </ojp:Params> </ojp:OJPTripRequest> </ServiceRequest> </OJPRequest> </OJP>"""
parse_ojp(x)
/home/skinkie/Sources/ojp-nova/venv/lib/python3.11/site-packages/xsdata/formats/converter.py:83: ConverterWarning: Failed to convert value `2023-08-08T12:51:28+0200` to one of (<class 'xsdata.models.datatype.XmlDateTime'>,)
```

**Comment by ue71603** [comment]
very uncool as this is a bug in SOAPUI then.
