### ISSUE TITLE
The service does not handle FareRequests in the past in a proper way. It results in an error instead of a sensible result

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#31]
Tested it with the attached file

File assumes 8.8.  at 8:xx
Did it at 8.8. 13:42
[input.zip](https://github.com/openTdataCH/ojp-nova/files/12290756/input.zip)

**Comment by skinkie** [comment]
So what should be the sensible result?

**Comment by ue71603** [comment]
I guess an "empty" response with a FARE_OUTOFRANGE error.

**Comment by ue71603** [comment]
error now handled.
