### ISSUE TITLE
Can you add some resources to the xsdata library to readme.md?

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#37]

**Comment by skinkie** [comment]
What do you mean exactly? Like where to find it, how to generate the schema's which are not publicly available anyway?

**Comment by ue71603** [comment]
xsdata is rather crucial for the works of this project, so having a link to their program, docu, examples etc might be helpful. If you think not, then you may close this issue.

**Comment by skinkie** [comment]
It really depends. If upstream does not allow us to share their XSDs, xsdata is maybe important as dependency; for example for datetime handling, but not for the generation of the schema's. For us obviously if we ever want to update the schema, we must know what commands to execute.
