### ISSUE TITLE
Wrong price

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-nova#49]
Not sure if this issue is on the ojp-nova or on the nova server, but here we go
<img width="573" alt="image" src="https://github.com/user-attachments/assets/66e1ca2b-5171-4149-be32-243d413bc9d0">

For the bus connection Visp - Saas Fee we get a 1st class price of 128.- CHF 
https://tools.odpch.ch/ojp-demo-v2/search?from=8571075&to=8501782&do_search=yes

OJP TR request (body to ojp-nova): https://gist.github.com/vasile/77c77fdf7c920b24ecb63b193c95ad27 
Nova response: https://gist.github.com/vasile/0858904c1087dcfec22dae380e37dcb9

**Comment by ue71603** [comment]
Last week Christoph found also an example at the italy border
[https://gist.github.com/vasile/146247c38839f9f4d9f3861ce214bf65](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fvasile%2F146247c38839f9f4d9f3861ce214bf65&data=05%7C02%7Cmatthias.guenter%40sbb.ch%7C4c16cb81a85c4e625c5508dcd25af617%7C2cda5d11f0ac46b3967daf1b2e1bd01a%7C0%7C0%7C638616535325151764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=m9oXeT%2BdbIm1JwDw0V73OYx%2FJExj4bRtJ3%2B8ka%2BhhLs%3D&reserved=0)

**Comment by ue71603** [comment]
`
Das Problem bei Deinem Fall ist, dass das Fixpreismodell nicht wissen kann, ob die Verbindung nur in der 2. Klasse ist oder nicht und bietet die Spartageskarte 80040 an, falls es noch Kontingent gibt. In diesem konkreten Fall antwortet NOVA mit dem Produkt 125 für DV-Modell  aber nur in der Klasse 2 und da es keine weiteren DV-Angebote in der Klasse 1 gibt, findet NOVA die Spartageskarte für die Klasse 1, weil wir für dieses Fixpreisprodukt nicht definieren können, dass für bestimmte  Strecken nur die Angebote in der Klasse 2. angeboten werden dürfen.

`

Die Tagesparkarten u.ä. müssen in der Antwort ausgeschlossen werden Werde ich machen.
