### ISSUE TITLE
We currently answer with siri: as the default name space => Should change

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#51]
otherwise copying and pasting from all our other sources won't work

**Comment by skinkie** [comment]
I don't see why it should change. A default namespace is just the _default_ and all others should be explicitly mentioned with a prefix. From (correct) XML parser perspective: it is transparent.

**Comment by ue71603** [comment]
I will do it, because I need it for the api-explorer where people copy their trips by hand in and this will go awfully bad, if they try to do this with different  name space handling.  What I want is a homogenous handling in all our platforms.

**Comment by skinkie** [comment]
So they don't paste complete requests, but parts in... aweful.

**Comment by ue71603** [comment]
Well, they have made a TripRequest and need to paste the Trips into the Fare Request template. Obiously it's cut and paste. Perhaps I create a java script to do it as git page.

Or we have a new function that thas TR - FR in one go

**Comment by ue71603** [comment]
will wait for the code from Vasile. closing here
https://github.com/openTdataCH/ojp-nova/tree/feature/extend-api
