### ISSUE TITLE
Using 850050 -> 8507000 has no trip

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#6]
If no trip can be found a suitable error should be returned.
It dosn't make sense to start the Nova request then.

**Comment by skinkie** [comment]
@ue71603 no nova request is started, unless then there is a tripresult right?

**Comment by ue71603** [comment]
I think it was started an created an error.

**Comment by skinkie** [comment]
https://github.com/openTdataCH/ojp-nova/blob/master/server.py#L25

This should be explicitly checked then. But I guess also an OJP error 'in protocol'.
