### ISSUE TITLE
Zwischenhalt ist in my view not done correctly.

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#7]
* Every intermediate stop must be part of a "zwischenHaltContext"
* The behaviour of the nova_request does not really fit the trip in my view 8507869  https://opentdatach.github.io/ojp-demo-app/search?from=8507869&to=8574945&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2023-04-20%2021:16&stage=prod

**Comment by skinkie** [comment]
@ue71603 do you mean stops where the vehicle does not stop? Because that might require us to replan (refine request).

**Comment by ue71603** [comment]
Example: 
Test: BLS Trainsplitting part 2
Bern:  8507000

Neuenburg: 8504221

Abfahrt 15::56

Verwaltungscode: 33

Code: "S"

Zugnummer:  15556

Zwischenhalte:

Bern Bümpliz Nord: 8504489
Bern Brünnen Westside: 8516154
Rosshäusern: 8504487
Gümmenen: 8504486
Kerzers: 8504400
Müntschemir 8504484
Ins: 8504483
Gampelen: 8504482
Zihlbrücke: 8504490
Marin-Epagnier: 8504481
St-Blaise-Lac: 8504480
We might have problems with the train number between Kerzers and Murten.

relevant Query:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <nova-preisauskunft:erstellePreisAuskunft xmlns:base="http://nova.voev.ch/services/v14/base" xmlns:vb="http://nova.voev.ch/services/v14/vertriebsbase" xmlns:nova-preisauskunft="http://nova.voev.ch/services/v14/preisauskunft" xmlns:ns21="http://nova.voev.ch/services/v14/vertrieb" xmlns="http://nova.voev.ch/services/v14/vertrieb">
      <nova-preisauskunft:PreisAuskunftRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="nova-preisauskunft:VerbindungPreisAuskunftRequest" nova-preisauskunft:kundenSegmenteGruppieren="false">
        <nova-preisauskunft:clientIdentifier base:leistungsVermittler="11" base:kanalCode="41" base:verkaufsStelle="16437" base:vertriebsPunkt="16437" base:verkaufsGeraeteId="236"/>
        <nova-preisauskunft:correlationKontext>
          <base:correlationId>87482634-560b-4da3-b6a1-155c37490fed</base:correlationId>
          <base:geschaeftsProzessId>1781786f-57ba-4e9a-bc29-287e2aa97f9a</base:geschaeftsProzessId>
        </nova-preisauskunft:correlationKontext>
        <nova-preisauskunft:angebotsFilter xsi:type="vb:TaxonomieFilter">
          <vb:produktTaxonomie>Basistaxonomie</vb:produktTaxonomie>
          <vb:taxonomieKlassePfad>
            <vb:klassenName>Einzelbillette</vb:klassenName>
          </vb:taxonomieKlassePfad>
        </nova-preisauskunft:angebotsFilter>
        <nova-preisauskunft:reisender nova-preisauskunft:alter="33" nova-preisauskunft:externeReisendenReferenzId="1234" nova-preisauskunft:reisendenTyp="PERSON"/>
        <nova-preisauskunft:verbindung nova-preisauskunft:externeVerbindungsReferenzId="e38add4e-2f67-4003-990b-9c7f08815b22">
          <nova-preisauskunft:segmentHinFahrt ns21:einstieg="8507000" ns21:ausstieg="8504221" ns21:verwaltungsCode="000033" ns21:abfahrtsZeit="2022-11-02T15:56:00.000+01:00" ns21:ankunftsZeit="2022-11-02T17:03:00.000+01:00">
            <ns21:verkehrsMittel ns21:gattungsCode="S" ns21:verkehrsMittelNummer="15556"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504489" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8516154" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504487" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504486" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504400" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504484" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504483" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504482" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504490" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504481" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8504480" ns21:tripContext="PLANNED"/>
          </nova-preisauskunft:segmentHinFahrt>
        </nova-preisauskunft:verbindung>
      </nova-preisauskunft:PreisAuskunftRequest>
    </nova-preisauskunft:erstellePreisAuskunft>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by ue71603** [comment]
A case with a discount ticket (when 2 weeks in the future and when available) And with train splitting

Start: Bern 8507000

Ziel: Goppenstein 8507474

Segment
Münsingen 8507006
Thun 8507100
Spiez 8507483
Segment
Mülenen 8507481
Reichenbach im Kandertal 8507480
Frutigen 8507478
Kandersteg 8507475

![image](https://user-images.githubusercontent.com/24227470/233471240-6b26cc07-1475-46e6-a5f3-9d9788765908.png)


Expected request:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <nova-preisauskunft:erstellePreisAuskunft xmlns:base="http://nova.voev.ch/services/v14/base" xmlns:vb="http://nova.voev.ch/services/v14/vertriebsbase" xmlns:nova-preisauskunft="http://nova.voev.ch/services/v14/preisauskunft" xmlns:ns21="http://nova.voev.ch/services/v14/vertrieb" xmlns="http://nova.voev.ch/services/v14/vertrieb">
      <nova-preisauskunft:PreisAuskunftRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="nova-preisauskunft:VerbindungPreisAuskunftRequest" nova-preisauskunft:kundenSegmenteGruppieren="false">
        <nova-preisauskunft:clientIdentifier base:leistungsVermittler="11" base:kanalCode="41" base:verkaufsStelle="16437" base:vertriebsPunkt="16437" base:verkaufsGeraeteId="236"/>
        <nova-preisauskunft:correlationKontext>
          <base:correlationId>87482634-560b-4da3-b6a1-155c37490fed</base:correlationId>
          <base:geschaeftsProzessId>1781786f-57ba-4e9a-bc29-287e2aa97f9a</base:geschaeftsProzessId>
        </nova-preisauskunft:correlationKontext>
        <nova-preisauskunft:angebotsFilter xsi:type="vb:TaxonomieFilter">
          <vb:produktTaxonomie>Basistaxonomie</vb:produktTaxonomie>
          <vb:taxonomieKlassePfad>
            <vb:klassenName>Einzelbillette</vb:klassenName>
          </vb:taxonomieKlassePfad>
        </nova-preisauskunft:angebotsFilter>
        <nova-preisauskunft:reisender nova-preisauskunft:alter="33" nova-preisauskunft:externeReisendenReferenzId="1234" nova-preisauskunft:reisendenTyp="PERSON"/>
        <nova-preisauskunft:verbindung nova-preisauskunft:externeVerbindungsReferenzId="e38add4e-2f67-4003-990b-9c7f08815b22">
          <nova-preisauskunft:segmentHinFahrt ns21:einstieg="8507000" ns21:ausstieg="8507483" ns21:verwaltungsCode="000033" ns21:abfahrtsZeit="2022-11-25T14:49:00.000+01:00" ns21:ankunftsZeit="2022-11-25T15:10:00.000+01:00">
            <ns21:verkehrsMittel ns21:gattungsCode="RE" ns21:verkehrsMittelNummer="4175"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507006" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507100" ns21:tripContext="PLANNED"/>
          </nova-preisauskunft:segmentHinFahrt>
           <nova-preisauskunft:segmentHinFahrt ns21:einstieg="8507483" ns21:ausstieg="8507474" ns21:verwaltungsCode="000033" ns21:abfahrtsZeit="2022-11-25T15:12:00.000+01:00" ns21:ankunftsZeit="2022-11-25T15:54:00.000+01:00">
            <ns21:verkehrsMittel ns21:gattungsCode="RE" ns21:verkehrsMittelNummer="4275"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507481" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507480" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507478" ns21:tripContext="PLANNED"/>
            <ns21:zwischenHaltContext ns21:uicCode="8507475" ns21:tripContext="PLANNED"/>
          </nova-preisauskunft:segmentHinFahrt>
        </nova-preisauskunft:verbindung>
      </nova-preisauskunft:PreisAuskunftRequest>
    </nova-preisauskunft:erstellePreisAuskunft>
  </soapenv:Body>
</soapenv:Envelope>

**Comment by ue71603** [comment]
It stops there, but they are intermediate.  E.g. you board in Bern, the train stops in Olten, and then you alight the train in Basel.

**Comment by skinkie** [comment]
@ue71603 lets discuss this... I'll explain my reasoning.

**Comment by ue71603** [comment]
You can get that with IncludeIntermediateStops
